dist: trusty
language: node_js
node_js:
  - stable
script:
  - npm run coverage
after_success:
  - npm run publish-coverage
notifications:
email:
  recipients:
    - frmm97@gmail.com
  on_success: never
  on_failure: always
